import { Data, IProductInput, IUserInput } from '@/types'
import { toSlug } from './utils'
import bcrypt from 'bcryptjs'
import { i18n } from '@/i18n-config'

/* ================= USERS ================= */
const users: IUserInput[] = [
  {
    name: 'Admin',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'Admin',
    address: {
      fullName: 'Admin User',
      street: 'Seoul Tech Street',
      city: 'Seoul',
      province: 'Seoul',
      postalCode: '12345',
      country: 'Korea',
      phone: '+82-10-0000-0000',
    },
    paymentMethod: 'Stripe',
    emailVerified: true,
  },
]

/* ================= PRODUCTS ================= */
const products: IProductInput[] = [
  /* ================= BATTERY ================= */
  {
    name: '18650 Lithium Ion Battery Cell',
    slug: toSlug('18650 Lithium Ion Battery Cell'),
    category: 'Battery',
    subcategory: 'Cylindrical',
    subSubcategory: 'Li-ion',
    images: ['/images/battery1.jpg'],
    brand: 'Generic',
    price: 5.5,
    listPrice: 7,
    countInStock: 100,
    description: 'High performance Li-ion cylindrical battery.',
    isPublished: true,
    tags: ['featured'],
    avgRating: 4.5,
    numReviews: 10,
    ratingDistribution: [],
    numSales: 20,
    sizes: [],
    colors: [],
    reviews: [],
  },

  {
    name: 'Prismatic LiFePO4 Battery Pack',
    slug: toSlug('Prismatic LiFePO4 Battery Pack'),
    category: 'Battery',
    subcategory: 'Prismatic',
    subSubcategory: 'LiFePO4',
    images: ['/images/battery2.jpg'],
    brand: 'EVE',
    price: 120,
    listPrice: 150,
    countInStock: 50,
    description: 'Safe and long-life LiFePO4 prismatic battery.',
    isPublished: true,
    tags: ['new-arrival'],
    avgRating: 4.8,
    numReviews: 5,
    ratingDistribution: [],
    numSales: 12,
    sizes: [],
    colors: [],
    reviews: [],
  },

  /* ================= BMS ================= */
  {
    name: 'Smart BMS 100A',
    slug: toSlug('Smart BMS 100A'),
    category: 'BMS',
    subcategory: 'Smart BMS',
    subSubcategory: 'Standard',
    images: ['/images/bms1.jpg'],
    brand: 'DALY',
    price: 80,
    listPrice: 100,
    countInStock: 40,
    description: 'Smart BMS with Bluetooth monitoring.',
    isPublished: true,
    tags: ['best-seller'],
    avgRating: 4.6,
    numReviews: 8,
    ratingDistribution: [],
    numSales: 25,
    sizes: [],
    colors: [],
    reviews: [],
  },

  /* ================= EMBEDDED ================= */
  {
    name: 'Forlinx Embedded Board',
    slug: toSlug('Forlinx Embedded Board'),
    category: 'Embedded',
    subcategory: 'Forlinx Products',
    subSubcategory: 'BC Board',
    images: ['/images/embedded1.jpg'],
    brand: 'Forlinx',
    price: 220,
    listPrice: 260,
    countInStock: 20,
    description: 'Industrial embedded computing board.',
    isPublished: true,
    tags: ['featured'],
    avgRating: 4.7,
    numReviews: 6,
    ratingDistribution: [],
    numSales: 10,
    sizes: [],
    colors: [],
    reviews: [],
  },

  /* ================= CHARGERS ================= */
  {
    name: '48V AC-DC Charger',
    slug: toSlug('48V AC-DC Charger'),
    category: 'Chargers',
    subcategory: 'AC-DC Charger',
    subSubcategory: '48V',
    images: ['/images/charger1.jpg'],
    brand: 'Voltro',
    price: 150,
    listPrice: 180,
    countInStock: 30,
    description: 'High efficiency AC-DC charger.',
    isPublished: true,
    tags: ['featured'],
    avgRating: 4.4,
    numReviews: 7,
    ratingDistribution: [],
    numSales: 15,
    sizes: [],
    colors: [],
    reviews: [],
  },

  /* ================= POWER SYSTEM ================= */
  {
    name: '220V AC Inverter',
    slug: toSlug('220V AC Inverter'),
    category: 'Power Conversion Systems',
    subcategory: 'Inverter',
    subSubcategory: '220Vac',
    images: ['/images/inverter1.jpg'],
    brand: 'Voltro',
    price: 300,
    listPrice: 350,
    countInStock: 25,
    description: 'Stable power inverter system.',
    isPublished: true,
    tags: ['new-arrival'],
    avgRating: 4.3,
    numReviews: 5,
    ratingDistribution: [],
    numSales: 9,
    sizes: [],
    colors: [],
    reviews: [],
  },

  /* ================= COMPONENTS ================= */
  {
    name: 'Battery Connector XT60',
    slug: toSlug('Battery Connector XT60'),
    category: 'Components',
    subcategory: 'Connector',
    subSubcategory: 'XT60',
    images: ['/images/component1.jpg'],
    brand: 'Generic',
    price: 2.5,
    listPrice: 3,
    countInStock: 500,
    description: 'High quality connector.',
    isPublished: true,
    tags: ['best-seller'],
    avgRating: 4.9,
    numReviews: 50,
    ratingDistribution: [],
    numSales: 200,
    sizes: [],
    colors: [],
    reviews: [],
  },
]

/* ================= DATA EXPORT ================= */
const data: Data = {
  users,
  products,
  reviews: [],
  webPages: [],
  headerMenus: [],
  carousels: [],
  settings: [
    {
      common: {
        freeShippingMinPrice: 50,
        isMaintenanceMode: false,
        defaultTheme: 'Light',
        defaultColor: 'Blue',
        pageSize: 12,
      },
      site: {
        name: 'VOLTRO',
        description: 'Industrial Battery & Power Systems',
        url: 'http://localhost:3000',
        keywords:
          'battery, bms, lithium battery, charger, inverter, power systems',
        author: 'VOLTRO Team',
        copyright: '2025-2026 VOLTRO Inc. All rights reserved.',
        logo: '/icons/logo.svg',
        slogan: 'Powering the Future',
        email: 'admin@voltro.com',
        address: 'Korea',
        phone: '+82-10-0000-0000',
      },
      availableLanguages: i18n.locales.map((l) => ({
        code: l.code,
        name: l.name,
      })),
      defaultLanguage: 'en-US',
      availableCurrencies: [
        { name: 'USD', code: 'USD', symbol: '$', convertRate: 1 },
        { name: 'KRW', code: 'KRW', symbol: '₩', convertRate: 1300 },
      ],
      defaultCurrency: 'USD',
      availablePaymentMethods: [
        { name: 'Stripe', commission: 0 },
        { name: 'PayPal', commission: 0 },
      ],
      defaultPaymentMethod: 'Stripe',
      carousels: [],
      availableDeliveryDates: [],
      defaultDeliveryDate: '',
    },
  ],
}

export default data
